# action.yml
name: 'ROS Style Guide C++ Formatter'
description: 'Formats using clang in ROS Stlye and commits changes'
author: Aaron Roller
branding:
  color: green
  icon: check-square
inputs:
  author-name:
    description: 'The name that will appear in commits when changes needs to be committed'
    required: false
    default: Format Bot
  author-email:
    description: 'The email address that will appear in commits when changes needs to be committed'
    required: false
    default: formatter@github.bot
  commit-message:
    description: 'The commit message used when changes need to be committed'
    required: false
    default: 'style: Applied ROS C++ Style Guide'
  branch:
    description: 'The branch the changes will be committed.'
    required: false
    default: 'None'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.author-name }}
    - ${{ inputs.author-email }}
    - ${{ inputs.commit-message }}
    - ${{ inputs.branch }}
