name: Testing formatter
on:
  push:
jobs:
  clang-format:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: test format
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git status
